[package]
name = "atomic-css-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rune = "0.13.1"
atomic-css-runtime = { path = "../atomic-css-runtime/" }
